import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {

      //Splash Screen
      'theory': 'Theory test in my language',
      'theory_description': 'I must write the real test will be in English language and this app just helps you to understand the materials in your language',

      //Onboard Screen
      'screen1_title': 'Best online courses in the world',
      'screen1_subTitle': 'Now you can learn anywhere, anytime, even if there is no internet access!',
      'screen2_title': 'Explore your new skill today',
      'screen2_subTitle': 'Our platform is designed to help you explore new skills. Let\'s learn & grow with Eduline!',
      'onboard_btn_next': 'Next',
      'onboard_btn_getStarted': 'Get Started',


      //SignIn
      'signIn_title': 'Welcome Back!',
      'signIn_subTitle': 'Please login first to start your Theory Test.',
      'email_address': 'Email Address',
      'password': 'Password',
      'remember_me': 'Remember Me',
      'forgot_password': 'Forgot Password',
      'sign_in': 'Sign In',
      'new_theory': 'New to Theory Test?',
      'create_account': 'Create Account',

      //SignUp

      'signUp_title': 'Welcome to Eduline',
      'signUp_subTitle': 'Let\'s join to eduline learning ecosystem & meet our professional mentor. It\'s Free!',
      'full_name': 'Full Name',
      'weak': 'Weak',
      'medium': 'Medium',
      'strong': 'Strong',
      'very_strong': 'Very Strong',
      'password_status': 'At least 8 characters with a combination of letters and Numbers',
      'label': 'Label',
      'already_account': 'Already have an account?',
      'sign_up': 'Sign Up',

      //SignUp Pob dailog
      'success_register': 'Successfully Registered',
      'success_sub_register': 'Your account has been registered successfully, now let\'s enjoy our features!',
      'continue': 'Continue',

      //Forgot Password
      'forgot_subTitle': 'Enter your email, we will send a verification code to email',

      //Reset Password
      'reset_password': 'Reset Password',
      'reset_subTitle': 'Your password must be at least 8 characters long and include a combination of letters, numbers',
      'new_password': 'New Password',
      'confirm_password': 'Confirm New Password',
      'submit': 'Submit',

      //Verify Code
      'verify_code': 'Verify Code',
      'verify_subTitle': 'Please enter the code we just sent to email',
      'resend_code': 'Resend Code',

      //Reset Pop Dailog
      'reset_pop_btn': 'Continue',
      'reset_pop_title': 'Success',
      'reset_pop_subTitle': 'Your Password is successfully created',

      // Enable Location Screen
      'enable_location_title': 'Enable Location',
      'enable_location_description': 'Kindly allow us to access your location to provide you with suggestions for nearby salons',
      'enable_button': 'Enable',
      'skip_button': 'Skip, Not Now',

      //Language Selection
      'mother_language': 'What is Your Mother Language',
      'select_language': 'Select Language',
      'discover_podcast': 'Discover what is a podcast description and podcast summary.',

      'selected': 'Selected',
      'select': 'Select',
      'next_screen': 'Next Screen',

      // Countries
      'united_states': 'United States',
      'bangladesh': 'Bangladesh',
      'india': 'India',
      'saudi_arabia': 'Saudi Arabia',
      'indonesia': 'Indonesia',
      'malaysia': 'Malaysia',
      'afghanistan': 'Afghanistan',
      'algeria': 'Algeria',
      'united_kingdom': 'United Kingdom',
      'canada': 'Canada',
      'australia': 'Australia',
      'japan': 'Japan',
      'germany': 'Germany',
    },
    'bn_BD': {
      'hello': 'হ্যালো',
      'welcome': 'স্বাগতম',
      'sign_in': 'সাইন ইন',
      'sign_up': 'সাইন আপ',
      'forgot_password': 'পাসওয়ার্ড ভুলে গেছেন',
      'mother_language': 'আপনার মাতৃভাষা কি',
      'select_language': 'ভাষা নির্বাচন করুন',
      'discover_podcast': 'পডকাস্ট বর্ণনা এবং পডকাস্ট সারাংশ কি তা আবিষ্কার করুন।',
      'continue': 'চালিয়ে যান',
      'selected': 'নির্বাচিত',
      'select': 'নির্বাচন করুন',
      'next_screen': 'পরবর্তী স্ক্রীন',

      // Countries
      'united_states': 'যুক্তরাষ্ট্র',
      'bangladesh': 'বাংলাদেশ',
      'india': 'ভারত',
      'saudi_arabia': 'সৌদি আরব',
      'indonesia': 'ইন্দোনেশিয়া',
      'malaysia': 'মালয়েশিয়া',
      'afghanistan': 'আফগানিস্তান',
      'algeria': 'আলজেরিয়া',
      'united_kingdom': 'যুক্তরাজ্য',
      'canada': 'কানাডা',
      'australia': 'অস্ট্রেলিয়া',
      'japan': 'জাপান',
      'germany': 'জার্মানি',
    },
    'ar_SA': {
      'hello': 'مرحبا',
      'welcome': 'أهلا وسهلا',
      'sign_in': 'تسجيل الدخول',
      'sign_up': 'إنشاء حساب',
      'forgot_password': 'نسيت كلمة المرور',
      'mother_language': 'ما هي لغتك الأم',
      'select_language': 'اختر اللغة',
      'discover_podcast': 'اكتشف ما هو وصف البودكاست وملخص البودكاست.',
      'continue': 'متابعة',
      'selected': 'المحدد',
      'select': 'اختر',
      'next_screen': 'الشاشة التالية',

      // Countries
      'united_states': 'الولايات المتحدة',
      'bangladesh': 'بنغلاديش',
      'india': 'الهند',
      'saudi_arabia': 'المملكة العربية السعودية',
      'indonesia': 'إندونيسيا',
      'malaysia': 'ماليزيا',
      'afghanistan': 'أفغانستان',
      'algeria': 'الجزائر',
      'united_kingdom': 'المملكة المتحدة',
      'canada': 'كندا',
      'australia': 'أستراليا',
      'japan': 'اليابان',
      'germany': 'ألمانيا',
    },
    'id_ID': {
      'hello': 'Halo',
      'welcome': 'Selamat datang',
      'sign_in': 'Masuk',
      'sign_up': 'Daftar',
      'forgot_password': 'Lupa Kata Sandi',
      'mother_language': 'Apa Bahasa Ibu Anda',
      'select_language': 'Pilih Bahasa',
      'discover_podcast': 'Temukan apa itu deskripsi podcast dan ringkasan podcast.',
      'continue': 'Lanjutkan',
      'selected': 'Dipilih',
      'select': 'Pilih',
      'next_screen': 'Layar Berikutnya',

      // Countries
      'united_states': 'Amerika Serikat',
      'bangladesh': 'Bangladesh',
      'india': 'India',
      'saudi_arabia': 'Arab Saudi',
      'indonesia': 'Indonesia',
      'malaysia': 'Malaysia',
      'afghanistan': 'Afganistan',
      'algeria': 'Aljazair',
      'united_kingdom': 'Inggris',
      'canada': 'Kanada',
      'australia': 'Australia',
      'japan': 'Jepang',
      'germany': 'Jerman',
    },
    'ms_MY': {
      'hello': 'Helo',
      'welcome': 'Selamat datang',
      'sign_in': 'Log Masuk',
      'sign_up': 'Daftar',
      'forgot_password': 'Lupa Kata Laluan',
      'mother_language': 'Apakah Bahasa Ibunda Anda',
      'select_language': 'Pilih Bahasa',
      'discover_podcast': 'Terokai apa itu penerangan podcast dan ringkasan podcast.',
      'continue': 'Teruskan',
      'selected': 'Dipilih',
      'select': 'Pilih',
      'next_screen': 'Skrin Seterusnya',

      // Countries
      'united_states': 'Amerika Syarikat',
      'bangladesh': 'Bangladesh',
      'india': 'India',
      'saudi_arabia': 'Arab Saudi',
      'indonesia': 'Indonesia',
      'malaysia': 'Malaysia',
      'afghanistan': 'Afghanistan',
      'algeria': 'Algeria',
      'united_kingdom': 'United Kingdom',
      'canada': 'Kanada',
      'australia': 'Australia',
      'japan': 'Jepun',
      'germany': 'Jerman',
    },
    'ps_AF': { // Pashto (Afghanistan)
      'hello': 'سلام',
      'welcome': 'ښه راغلست',
      'sign_in': 'ننوتل',
      'sign_up': 'ګڼون جوړول',
      'forgot_password': 'پاسورډ هیر کړی',
      'mother_language': 'ستاسو مورنی ژبه کومه ده',
      'select_language': 'ژبه وټاکئ',
      'discover_podcast': 'پوه شئ چې پوډکاسټ تشریح او پوډکاسټ لنډیز څه شی دی.',
      'continue': 'ادامه',
      'selected': 'ټاکل شوی',
      'select': 'ټاکل',
      'next_screen': 'بلی صفحه',

      // Countries
      'united_states': 'متحده ایالات',
      'bangladesh': 'بنګله دیش',
      'india': 'هند',
      'saudi_arabia': 'سعودی عربستان',
      'indonesia': 'اندونیزیا',
      'malaysia': 'مالیزیا',
      'afghanistan': 'افغانستان',
      'algeria': 'الجزایر',
      'united_kingdom': 'متحده پادشاهی',
      'canada': 'کانادا',
      'australia': 'آسټرالیا',
      'japan': 'جاپان',
      'germany': 'جرمني',
    },
    'ar_DZ': { // Arabic (Algeria)
      'hello': 'مرحبا',
      'welcome': 'أهلا بك',
      'sign_in': 'تسجيل الدخول',
      'sign_up': 'إنشاء حساب',
      'forgot_password': 'نسيت كلمة المرور',
      'mother_language': 'ما هي لغتك الأم',
      'select_language': 'اختر اللغة',
      'discover_podcast': 'اكتشف ما هو وصف البودكاست وملخص البودكاست.',
      'continue': 'استمر',
      'selected': 'المحدد',
      'select': 'اختر',
      'next_screen': 'الشاشة التالية',

      // Countries
      'united_states': 'الولايات المتحدة',
      'bangladesh': 'بنغلاديش',
      'india': 'الهند',
      'saudi_arabia': 'السعودية',
      'indonesia': 'إندونيسيا',
      'malaysia': 'ماليزيا',
      'afghanistan': 'أفغانستان',
      'algeria': 'الجزائر',
      'united_kingdom': 'المملكة المتحدة',
      'canada': 'كندا',
      'australia': 'أستراليا',
      'japan': 'اليابان',
      'germany': 'ألمانيا',
    },
  };
}